source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude the cocoapods/activesupport versions known to break the build.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'

# Ruby 3.4+/4.0 removed these from the standard library; CocoaPods'
# CFPropertyList dependency requires kconv (provided by nkf).
gem 'nkf'
gem 'tsort'
